#!/usr/bin/env bash
#
# Context Coach Installer
# Installs the Context Coach module into a BMAD project
#
# Usage: ./install.sh [project-path] [user-id]
#

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo ""
echo "=================================="
echo "  Context Coach Installer v0.1.0"
echo "=================================="
echo ""

# Get project path
PROJECT_PATH="${1:-$(pwd)}"
USER_ID="${2:-$USER}"

# Resolve to absolute path
PROJECT_PATH=$(cd "$PROJECT_PATH" && pwd)

echo "Project path: $PROJECT_PATH"
echo "User ID: $USER_ID"
echo ""

# Check if .bmad exists
if [[ ! -d "$PROJECT_PATH/.bmad" ]]; then
    echo -e "${YELLOW}Warning: .bmad directory not found. Creating...${NC}"
    mkdir -p "$PROJECT_PATH/.bmad"
fi

# Create directories
echo "Creating directories..."
mkdir -p "$PROJECT_PATH/.bmad/modules/context-coach"
mkdir -p "$PROJECT_PATH/.bmad/context-coach/journal"
mkdir -p "$PROJECT_PATH/.claude/hooks"

# Get installer directory
INSTALLER_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Copy module files
echo "Installing module files..."
if [[ -d "$INSTALLER_DIR/module" ]]; then
    cp "$INSTALLER_DIR/module/module.yaml" "$PROJECT_PATH/.bmad/modules/context-coach/"
    cp "$INSTALLER_DIR/module/journal-writer.md" "$PROJECT_PATH/.bmad/modules/context-coach/"
    cp "$INSTALLER_DIR/module/README.md" "$PROJECT_PATH/.bmad/modules/context-coach/"
    echo -e "${GREEN}✓ Module files installed${NC}"
else
    echo -e "${RED}Error: Module files not found at $INSTALLER_DIR/module${NC}"
    exit 1
fi

# Create config file
echo "Creating configuration..."
cat > "$PROJECT_PATH/.bmad/context-coach/config.yaml" << EOF
# Context Coach Configuration
# Generated by installer on $(date)

# Enable/disable prompt journaling
enabled: true

# Your identifier (for team tracking)
user_id: "$USER_ID"

# Journal storage location
journal_path: ".bmad/context-coach/journal"
EOF
echo -e "${GREEN}✓ Configuration created${NC}"

# Copy hook script
echo "Installing Claude Code hook..."
if [[ -f "$INSTALLER_DIR/hooks/context-coach-capture.sh" ]]; then
    cp "$INSTALLER_DIR/hooks/context-coach-capture.sh" "$PROJECT_PATH/.claude/hooks/"
    chmod +x "$PROJECT_PATH/.claude/hooks/context-coach-capture.sh"
    echo -e "${GREEN}✓ Hook script installed${NC}"
else
    echo -e "${YELLOW}Warning: Hook script not found, skipping...${NC}"
fi

# Check/update settings.json
SETTINGS_FILE="$PROJECT_PATH/.claude/settings.json"
if [[ -f "$SETTINGS_FILE" ]]; then
    echo -e "${YELLOW}Note: .claude/settings.json exists.${NC}"
    echo "To enable the hook, add this to your hooks configuration:"
    echo ""
    echo '  "PreToolUse": ['
    echo '    {'
    echo '      "matcher": ".*",'
    echo '      "hooks": ['
    echo '        {'
    echo '          "type": "command",'
    echo '          "command": "bash \"$CLAUDE_PROJECT_DIR\"/.claude/hooks/context-coach-capture.sh",'
    echo '          "timeout": 5'
    echo '        }'
    echo '      ]'
    echo '    }'
    echo '  ]'
    echo ""
else
    echo "Creating settings.json with hook..."
    cat > "$SETTINGS_FILE" << 'EOF'
{
  "$schema": "https://json.schemastore.org/claude-code-settings.json",
  "hooks": {
    "PreToolUse": [
      {
        "matcher": ".*",
        "hooks": [
          {
            "type": "command",
            "command": "bash \"$CLAUDE_PROJECT_DIR\"/.claude/hooks/context-coach-capture.sh",
            "timeout": 5
          }
        ]
      }
    ]
  }
}
EOF
    echo -e "${GREEN}✓ Settings.json created with hook${NC}"
fi

echo ""
echo "=================================="
echo -e "${GREEN}Installation Complete!${NC}"
echo "=================================="
echo ""
echo "Context Coach is now installed."
echo ""
echo "Your prompts will be logged to:"
echo "  $PROJECT_PATH/.bmad/context-coach/journal/"
echo ""
echo "To view your prompts:"
echo "  cat .bmad/context-coach/journal/\$(date +%Y-%m-%d).jsonl | jq ."
echo ""
echo "To disable, edit:"
echo "  $PROJECT_PATH/.bmad/context-coach/config.yaml"
echo "  Set enabled: false"
echo ""
